# Read the Docs configuration file (v2)
version: 2

# Build environment
build:
  os: ubuntu-24.04
  tools:
    # Use a stable Python version; 3.11 is recommended for Sphinx 9 compatibility
    python: "3.11"

# Ensure RTD installs docs dependencies and your package
python:
  install:
    - requirements: docs/requirements-docs.txt
    - path: .

# Sphinx config path
sphinx:
  configuration: docs/conf.py

# Optionally enable system packages (rarely needed)
# system_packages: false
